# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: cec19f7642dc280a644a536dac4710bd8632dbea062db43aa327ab009e5316de8eaa45771f56b8afb45f82a8c5fb3efa010e9006dc31e6747e970422dbf78d39

test:
  secret_key_base: 4bb6a13c77af17a1796bf9e442fc287bc4393ce031eedd13848a984c27fce1049bb55a99b87ec39a28b164ca2c2c6652ccdfb71af40284b1d3d6fc1a892c1201

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
